version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgres://user:ISccWttNk5oo0E3G1hcS32yVr6CBvt1X@dpg-cgi2te02qv2772h7mdjg-a/flask_v06g
      CONFIG_NAME: DevConfig
      restart: always
#    volumes:
#      - ./blog:/app/blog
    ports:
      - 8080:5000
    depends_on:
      - db

  db:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_DB: flask_v06g
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ISccWttNk5oo0E3G1hcS32yVr6CBvt1X
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: